# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/minimipsb3/minimips/minimips.cache/wt [current_project]
set_property parent.project_path F:/minimipsb3/minimips/minimips.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files F:/minimipsb3/romnew.coe
add_files -quiet F:/minimipsb3/minimips/minimips.runs/irom_synth_1/irom.dcp
set_property used_in_implementation false [get_files F:/minimipsb3/minimips/minimips.runs/irom_synth_1/irom.dcp]
read_verilog F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/defines.v
set_property file_type "Verilog Header" [get_files F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/defines.v]
read_verilog -library xil_defaultlib {
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/ID.v
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/MEM_WB.v
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/EX.v
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/EX_MEM.v
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/ID_EX.v
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/RegFile.v
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/PC.v
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/IF_ID.v
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/MEM.V
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/WB.v
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/miniMIPS_Top.v
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/confreg.v
  F:/minimipsb3/minimips/minimips.srcs/sources_1/imports/src/Basys3_Top.v
}
read_xdc F:/minimipsb3/minimips/minimips.srcs/constrs_1/imports/miniMIPS_B3.srcs/Basys-3.xdc
set_property used_in_implementation false [get_files F:/minimipsb3/minimips/minimips.srcs/constrs_1/imports/miniMIPS_B3.srcs/Basys-3.xdc]

catch { write_hwdef -file Basys3_Top.hwdef }
synth_design -top Basys3_Top -part xc7a35tcpg236-1
write_checkpoint -noxdef Basys3_Top.dcp
catch { report_utilization -file Basys3_Top_utilization_synth.rpt -pb Basys3_Top_utilization_synth.pb }
